version: "3.8"
services:
  # Backend (API service)
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "3001:3001" # Map API service to port 3001
    volumes:
      - ./apps/api:/app # Mount the local API folder for live-reloading
      - /app/node_modules # Ignore node_modules to avoid performance issues
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydatabase
    networks:
      - my-network

  # Frontend (Web service)
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "3000:3000" # Map web service to port 3000
    volumes:
      - ./apps/web:/app # Mount the local Web folder for live-reloading
      - /app/node_modules # Ignore node_modules to avoid performance issues
    depends_on:
      - api
    networks:
      - my-network

  # PostgreSQL Database
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network

# Volumes for persistent data
volumes:
  pgdata:

# Network for all services
networks:
  my-network:
